name: movie_flix
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Retrofit
  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1

  sprintf: ^7.0.0

  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #Retrofit
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true